import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const NotoSans = localFont({
  src: './fonts/NotoSansKR-VariableFont_wght.ttf',
  variable: "--font-Noto-Sans",
  weight: '45 920',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${NotoSans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
