import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ApolloUploadSetting from "@/commons/settings/apollo-upload-setting";
import Layout from "@/commons/layout";

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  variable: "--font-pretendard-variable",
  display: 'swap',
  weight: '45 920',
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="ko">
      <body
        className={`${pretendard.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloUploadSetting>
          <Layout>
            {children}
          </Layout>
        </ApolloUploadSetting>
      </body>
    </html>
  );
}
